version: '3.3'
services:
  db:
    image: mysql:5.7
    # restart: always
    environment:
      MYSQL_DATABASE: 'fastapi_playground'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mauricio'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
  web:
    build:
      context: ./  # 5
      dockerfile: Dockerfile  # 6
    command: bash -c "python3 app/main.py"
    depends_on:
      - db
    ports:
      - "8000:8000"  # 7
    volumes:
      - ./:/backend  # binding mount one folder to the other

volumes:
  my-db: