"""cpf_to_str_with_config

Revision ID: 0951e499c28b
Revises: 3735add7606b
Create Date: 2022-01-20 08:22:29.951682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0951e499c28b'
down_revision = '3735add7606b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'cpf',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'cpf',
               existing_type=sa.String(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.String(length=760),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
