"""add item in user

Revision ID: 8be0a2dbb26a
Revises: eb7658256b1d
Create Date: 2022-04-22 14:11:55.521737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be0a2dbb26a'
down_revision = 'eb7658256b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('items', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'items')
    # ### end Alembic commands ###
