"""do nothing

Revision ID: abcf3b6ec522
Revises: 8be0a2dbb26a
Create Date: 2022-04-22 15:01:24.605747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcf3b6ec522'
down_revision = '8be0a2dbb26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
