"""cpf_to_str_2

Revision ID: 3735add7606b
Revises: fa0c5aa2c735
Create Date: 2022-01-20 08:05:50.593799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3735add7606b'
down_revision = 'fa0c5aa2c735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
