"""table again_fuck

Revision ID: 9ef7afbe192c
Revises: f617ad46c0fc
Create Date: 2022-01-20 08:02:38.553973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef7afbe192c'
down_revision = 'f617ad46c0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
